### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by nluetts** [adnidor/vc820py#1]
Hi there,

I would like to use your code to read out a Voltcraft VC820, but this requires that you permit reuse/modification in an appropriate open source license.
May I kindly ask that you add a license to this repository? :-)

**Comment by adnidor** [comment]
Hi nluetts,

I've put put this code under the GPL. Thank you for your interest!

**Comment by nluetts** [comment]
Super, thank you very much for uploading this code!
